[package]
name = "test"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ 
    "tagged_binary_serialization",
    "tagged_binary_serialization_encoder"
]


[dependencies]
tagged_binary_serialization = { path = "./tagged_binary_serialization" }
tagged_binary_serialization_encoder = { path = "./tagged_binary_serialization_encoder" }
